# Copyright (c) 2016-2018 Dell Inc. or its subsidiaries.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resource_registry:
  OS::TripleO::Network::Ports::StorageMgmtVipPort: ./overcloud/network/ports/ctlplane_vip.yaml
  OS::TripleO::Controller::Ports::StorageMgmtPort: ./overcloud/network/ports/noop.yaml


parameter_defaults:
  # CHANGEME: Change the following to the desired MTU for Neutron Networks
  NeutronGlobalPhysnetMtu: 1500
  # CHANGEME: Change the following to the CIDR for the Management network
  ManagementNetCidr: 192.168.110.0/24

  # CHANGEME: Change the following to the CIDR for the Private API network
  InternalApiNetCidr: 192.168.140.0/24

  # CHANGEME: Change the following to the CIDR for the Tenant network
  TenantNetCidr: 192.168.130.0/24

  # CHANGEME: Change the following to the CIDR for the Storage network
  StorageNetCidr: 192.168.170.0/24

  # CHANGEME: Change the following to the CIDR for the Storage Clustering network
  StorageMgmtNetCidr: 192.168.180.0/24

  # CHANGEME: Change the following to the CIDR for the External network
  ExternalNetCidr: 192.168.190.0/24

  # CHANGEME: Change the following to the DHCP ranges for the iDRACs to use on
  # the Management network
  ManagementAllocationPools: [{'start': '192.168.110.10', 'end': '192.168.110.149'}]

  # The allocation pools below are used to dynamically assign DHCP IP addresses
  # to the various networks on the overcloud nodes as they are provisioned.  If
  # using static IPs instead, see static-ip-environment.yaml.

  # CHANGEME: Change the following to the DHCP range to use on the
  # Private API network
  InternalApiAllocationPools: [{'start': '192.168.140.121', 'end': '192.168.140.250'}]

  # CHANGEME: Change the following to the DHCP range to use on the
  # Tenant network
  TenantAllocationPools: [{'start': '192.168.130.121', 'end': '192.168.130.250'}]

  # CHANGEME: Change the following to the DHCP range to use on the
  # Storage network
  StorageAllocationPools: [{'start': '192.168.170.121', 'end': '192.168.170.250'}]

  # CHANGEME: Change the following to the DHCP range to use on the
  # Storage Clustering network
  StorageMgmtAllocationPools: [{'start': '192.168.180.121', 'end': '192.168.180.250'}]

  # CHANGEME: Change the following to the DHCP range to use on the
  # External network
  ExternalAllocationPools: [{'start': '192.168.190.121', 'end': '192.168.190.250'}]

  # CHANGEME: Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 192.168.190.1

  # CHANGEME: Set to the router gateway on the management network
  ManagementNetworkGateway: 192.168.110.1

  # CHANGEME: Set to the IP of the gateway on the provisioning network which
  # will allow access to the management network
  ProvisioningNetworkGateway: 192.168.120.1

  # CHANGEME: Set to the router gateway on the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.120.13

  # CHANGEME: Set to the CIDR of the control plane network
  ControlPlaneSubnetCidr: "24"

  # CHANGEME: Set to the IP address of the Undercloud
  EC2MetadataIp: 192.168.120.13

  # CHANGEME: Set to the DNS servers to use for the overcloud nodes (maximum 2)
  DnsServers: ["8.8.8.8", "8.8.4.4"]

  # CHANGEME: Change the following to the VLAN ID to use on the
  # Private API network
  InternalApiNetworkVlanID: 140

  # CHANGEME: Change the following to the VLAN ID to use on the
  # Storage network
  StorageNetworkVlanID: 170

  # CHANGEME: Change the following to the VLAN ID to use on the
  # Storage Clustering network
  StorageMgmtNetworkVlanID: 180

  # CHANGEME: Change the following to the VLAN ID to use on the
  # Tenant network
  TenantNetworkVlanID: 130

  # CHANGEME: Change the following to the VLAN ID to use on the
  # External network
  ExternalNetworkVlanID: 190
  # CHANGEME: Change the following to the MTU value to use on the
  # External network
  ExternalNetworkMTU: 1500
  # CHANGEME: Change the following to the MTU value to use on the
  # internal network  
  InternalApiMTU: 1500
  # CHANGEME: Change the following to the MTU value to use on the
  # Storage network
  StorageNetworkMTU: 1500
  # CHANGEME: Change the following to the MTU value to use on the
  # StorageMgmtNetwork network
  StorageMgmtNetworkMTU: 1500
  # CHANGEME: Change the following to the MTU value to use on the
  # TenantNetwork network
  TenantNetworkMTU: 1500
  # CHANGEME: Change the following to the MTU value to use on the
  # Provisioning network
  ProvisioningNetworkMTU: 1500
  # CHANGEME: Change the following to the MTU value to use on the
  # Management network
  ManagementNetworkMTU: 1500
  # CHANGEME: Change the following to the MTU value to use on the
  # Default Bonds MTU
  DefaultBondMTU: 9216
  
  # CHANGEME: Change the following to mtu size used for the floating network
  ExtraConfig:
    neutron::plugins::ml2::physical_network_mtus: physext:1500
  # CHANGEME: Set to empty string for External VLAN, br-ex if on native VLAN of br-ex
  NeutronExternalNetworkBridge: "''"
  ServiceNetMap:
    NeutronTenantNetwork: tenant
    CeilometerApiNetwork: internal_api
    AodhApiNetwork: internal_api
    GnocchiApiNetwork: internal_api
    MongoDbNetwork: internal_api
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    GlanceApiNetwork: storage
    GlanceRegistryNetwork: internal_api
    KeystoneAdminApiNetwork: ctlplane # allows undercloud to config endpoints
    KeystonePublicApiNetwork: internal_api
    NeutronApiNetwork: internal_api
    HeatApiNetwork: internal_api
    NovaApiNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    SwiftMgmtNetwork: storage # Changed from storage_mgmt
    SwiftProxyNetwork: storage
    SaharaApiNetwork: internal_api
    HorizonNetwork: internal_api
    MemcachedNetwork: internal_api
    RabbitMqNetwork: internal_api
    RedisNetwork: internal_api
    MysqlNetwork: internal_api
    CephClusterNetwork: storage_mgmt
    CephPublicNetwork: storage
    ControllerHostnameResolveNetwork: internal_api
    ComputeHostnameResolveNetwork: internal_api
    BlockStorageHostnameResolveNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    CephStorageHostnameResolveNetwork: storage
    NovaColdMigrationNetwork: internal_api
    NovaLibvirtNetwork: internal_api

