# This environment file enables Manila with the Unity backend.
resource_registry:
  OS::TripleO::Services::ManilaApi: ./overcloud/deployment/manila/manila-api-container-puppet.yaml
  OS::TripleO::Services::ManilaScheduler: ./overcloud/deployment/manila/manila-scheduler-container-puppet.yaml
  # Only manila-share is pacemaker managed:
  OS::TripleO::Services::ManilaShare: ./overcloud/deployment/manila/manila-share-pacemaker-puppet.yaml
  OS::TripleO::Services::ManilaBackendUnity: ./overcloud/deployment/manila/manila-backend-unity.yaml

parameter_defaults:
  ManilaUnityBackendName: tripleo_manila_unity
# DELL-NFV Overrides
  ManilaUnityDriverHandlesShareServers: <manila_unity_driver_handles_share_servers>
  ManilaUnityNasLogin: <manila_unity_nas_login>
  ManilaUnityNasPassword: <manila_unity_nas_password>
  ManilaUnityNasServer: <manila_unity_nas_server>
  ManilaUnityServerMetaPool: <manila_unity_server_meta_pool>
  ManilaUnityShareDataPools: <manila_unity_share_data_pools>
  ManilaUnityEthernetPorts: <manila_unity_ethernet_ports>
  ManilaUnityEmcSslCertVerify: <manila_unity_ssl_cert_verify>
  ManilaUnityEmcSslCertPath: <manila_unity_ssl_cert_path>
